#!/bin/bash
# Get pulsars 
fakePulsar -v  -cone "$1 $2 $3 $4 $5 $6 $7 $8 
$9" -ellipse "${10} ${11} ${12}" -cone "${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21}" -ellipse "${22} ${23} ${24}" -a "${25}" -b "${26}" -nb "2246" -np "620" -gg ${27}
pmod -templatedata weak.all37.p3fold -align -oformat ASCII -ext p3fold.ASCII ${27} 
