#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <errno.h>
#include <unistd.h>

#define PPROG "PPOLYCO: "

int verb1,verb2,verb3,verb4;

double convdtoe(char *instring);

void ppolyco(char *unfname,int imjd,double frmjd,double *pobs,double *phobs)
{
  
  FILE   *pfile;

  int    i,loop,ncoeff,nspan;

  char   bpha[10],nsite[2],polyname[2000],psrname[12],utdate[9];
  char   tmpstr[32],tmpstr2[32],tmpstr3[32],tmpline[100],extn[8];

  float  dearth,dm,rfreq,uttime,dbphase;
  
  double dt,bphase,phase,pfreq,rf0,rphase,tmid,tmjd,tmjd1,tmjd2;
  double *coeff=NULL;
/*    polyname = (char *) calloc(17,1); */
  memset(tmpline,0,100);
  memset(polyname,0,2000);
  tmjd = (double)(imjd+frmjd);
  strncpy(polyname,unfname,1024);
  strcpy(extn,".polyco");
  strncat(polyname,extn,7);

  if (access(polyname, R_OK) == 0)
    {
      pfile = fopen(polyname,"r");
    }
  else
    {
      fprintf(stderr,"No access to %s ... exiting\n",polyname);
      exit(-1);
    }
  tmid  = 0.0;
  tmjd1 = 0.0;
  tmjd2 = 0.0;
  loop = -1;

  while(tmjd > tmjd2)
    {
      loop++;
/*       fgets(tmpline,90,pfile); */
      fscanf(pfile,"%[^\n]s",tmpline);
      fseek(pfile,1,1);

      if (strlen(tmpline) > 81) 
      {
	      strncpy(psrname,tmpline,10);
        sscanf(tmpline+10,"%s %f %lf %f %f %f\n",utdate,&uttime,&tmid,&dm,&dearth,&dbphase);
      }
      else
      {
	      strncpy(psrname,tmpline,10); 
	sscanf(tmpline,"%s %f %lf %f %f\n",utdate,&uttime,&tmid,&dm,&dearth);
      }
      if (verb2) printf("%s %d %s %s %f %lf %f %f\n",
	     PPROG,loop,psrname,utdate,uttime,tmid,dm,dearth);


      fflush(stdout);
      fscanf(pfile,"%[^\n]s",tmpline);
      fseek(pfile,1,1);
      sscanf(tmpline,"%lf %lf %s %d %d %f %s\n",
	     &rphase,&rf0,nsite,&nspan,&ncoeff,&rfreq,bpha);
      if (verb2) printf("%s %d %lf %lf %s %d %d %f %s\n",
		       PPROG,loop,rphase,rf0,nsite,nspan,ncoeff,rfreq,bpha);
      
      tmjd1 = tmid - nspan/2880.0;     /* divide nspan by 2 and convert to fractional day*/
      tmjd2 = tmid + nspan/2880.0;
      
      if (tmjd < tmjd1 && loop < 1) {
	printf("%s MJD %lf out of polyco range\n",PPROG,tmjd);
	exit(0);
      }
      
      if (verb2) printf("%s tmjd %f tmjd1 %f tmjd2 %f\n",PPROG,tmjd,tmjd1,tmjd2);
      if (!coeff) coeff = (double *) calloc(ncoeff,8);
      
      for (i=0;i<ncoeff;i+=3)
	{ 
	  fscanf(pfile,"%[^\n]s",tmpline);
	  fseek(pfile,1,1);
	  sscanf(tmpline,"%s",tmpstr);
	  sscanf(tmpline,"%s %s %s",tmpstr,tmpstr2,tmpstr3);
	  coeff[i] = convdtoe(tmpstr);
	  coeff[i+1] = convdtoe(tmpstr2);
	  coeff[i+2] = convdtoe(tmpstr3);
	  if (verb3) {
	    printf("MAD %s coeffs: %.15e %.15e %.15e\n",
		   PPROG,coeff[i],coeff[i+1],coeff[i+2]);
	    printf("TMPSTR: %s %s %s",tmpstr,tmpstr2,tmpstr3);
	  }
	}
    }
  /* Calculating the phase and period at tmjd */

  dt = (double)((tmjd - tmid) * 1440);
  if (verb2) printf("MAD2 %s tmjd %20.10f tmid %20.10f DT = %f\n",PPROG,tmjd,tmid,dt);

  /* Initial parts of the expressions from tempo.man */ 
  bphase = (double) (rphase + (double)(dt*60.0*rf0));
  phase = 0.0;
  pfreq = rf0;

  if (verb2) printf("%s Outside Coeff loop phase = %lf pfreq = %.15f\n",PPROG,bphase,pfreq); 

  /* Adding in the coefficient contributions */
  for (i=0;i<ncoeff;i++)
    {
      phase = phase + coeff[i] * pow(dt,1.0*i);
      if (i > 0) 
	{
	  pfreq = pfreq + i*coeff[i]*pow(dt,1.0*(i-1))/60;
	}
      if (verb3) printf("%s coeff[%d] = %g change = %12.9f sum = %.7f pfreq = %.15f\n",
		       PPROG,i,coeff[i],coeff[i] * pow(dt,1.0*i),phase,pfreq); 
    }
  phase += bphase;
  if (verb2) printf("%s FiNaL phase is %20.7f\n",PPROG,phase);
  *pobs = 1.0/pfreq;
  *phobs = phase;
  fclose(pfile);
  if (coeff) 
    free(coeff); 
}




/* Stupid routine required because fortran uses a D for exponentation and C wants E */
/* and the polyco is generated by tempo which is a fortran program! */
double convdtoe(instring)
char *instring;
{
  char *dspot=strchr(instring, 'D');
  if (dspot)
     *dspot='e';
  return atof(instring);
  /* redwards here is the old memory leaky version... the calloced
   mem is totally lost, while instring is "freed", wherever it was...*/
#if 0
  char *tmpstr2,*tmpstr3;  
  int dspot;
  double outdouble;


  dspot = strcspn(instring,"D");
  tmpstr2 = (char *) calloc(dspot+5,1);
  tmpstr2 = instring;
  tmpstr2[dspot] = 'e';
  
  outdouble = atof(tmpstr2);
  /*   printf("tmpstr3 = %s tmpstr2 = %s instring = %soutdouble = %g\n",tmpstr3,tmpstr2,instring,outdouble); */
  return outdouble;

  free(tmpstr2);
/*   free(tmpstr3); */
#endif
}







